---
title: "about_proj"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(tidyverse)
library(janitor)  
library(gt)
library(dplyr)
library(rvest)
```

The Chicago Public Schools (CPS) district has been lacerated with budget
cuts, perpetuating a cycle of schools being forced to close, students being
displaced, and the district suffering. Put simply, the primary vehicle through
which funding is distributed is thought Student Based Budgeting (SBB), wherein
schools receive funding based on their enrollment. A small minority of schools,
named selective enrollment schools, draw most students' attention, causing
bustling waitlists, boatloads of resources, and stellar performances. But this
siphons enrollment from other schools in the district, which are often well
below capacity, meaning less funding is received and therefore programs at
those schools have to be cut. This makes schools even less appealing, and then
even less students enroll, perpetuating a vicious cycle until school closure.
This is disastrous for CPS students, especially those within the South side
of Chicago where conditions are very dangerous; a school closing means students
have to commute farther, and each longer second within such an unstable
environment is severely dangerous. This risk alone potentially deters many 
students from school, despite the ostensibly "helpful" school openings in 
their place. 

This is merely an oversimplified window into the obfuscated system that is the
Chicago Public Schools district. Despite being the third largest school 
district in the nation, they receive the 49th most funding per-capita, which
is abominable and feeds into these extremities. But the issue is that with 
such an unclear and complicated budget system, there isn't much transparency 
in regards to many of these issues; even when principals are asked, they
can speak to very little outside of their own budgets. I hope to use this
project as a platform to explore and illustrate concretely the impacts of
school closures and the consequences of the budget crises engulfing CPS.


Here are the links to my sources:

https://interactive.wbez.org/generation-school-closings/

https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRmKox-lDNqhtUNL4WLl8x6DljIi3b0k1pYEmD7adfCwX-rGYyFw0XIjxNWkOfL6og3CHfUEHPMwv6k/pubhtml?urp=gmail_link#

https://www.chicagotribune.com/news/ct-2016-cps-school-budget-cuts-table-htmlstory.html







