---
title: "about"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(tidyverse)
library(janitor)  
library(gt)
library(dplyr)
library(rvest)
```

URL to repo: https://github.com/ibskhan4/about.git

The Chicago Public Schools (CPS) district has been lacerated with budget
cuts, perpetuating a cycle of school being forced to close, students being
displaced, and the district suffering. Put simply, the primary vehicle through
which funding is distributed is thought Student Based Budgeting (SBB), wherein
schools receive funding based on their enrollment. A small minority of schools,
named selective enrollment schools, draw most students' attention, causing
bustling waitlists, boatloads of resources, and stellar performances. But this
siphons enrollment from other schools in the district, which are often well
below capacity, meaning less funding is received and therefore programs at
those schools have to be cut. This makes schools even less appealing, and then
even less studens enroll, perpetuating a vicious cycle until school closure.
This is disastrous for CPS students, especially those within the South side
of Chicago where conditions are very dangerous; a school closing means students
have to commute farther, and each longer second within such an unstable
environment is severely dangerous. This risk alone potentially deters many 
students from school, despite the ostensibly "helpful" school openings in 
their place. 

This is merely an oversimplified window into the obfuscated system that is the
Chicago Public Schools district. Despite being the third largest school 
district in the nation, they receive the 49th most funding per-capita, which
is abominable and feeds into these extremities. But the issue is that with 
such an unclear and complicated budget system, there isn't much transparency 
in regards to many of these issues; even when principals are asked, they
can speak to very little outside of their own budgets. I hope to use this
project as a platform to explore and illustrate concretely the impacts of
school closures and the consequences of the budget crises engulfing CPS.

What I am currently thinking is that I wish to use the data to construct 
an animated sort of map which chronologically displays the school closings and
the consequent impacts on displaced students as a result. The first dataset
I retrieved was from WBEZ Chicago, which compiled data regarding school 
closings, openings, and the number of students who were displaced from 2002 to
2018. From this, I was able to extract two tables which I regard to be very
relevant, one being a table listing all the schools which have closed 
throughout the years, and then a table of the number of impacted students
at the various high schools. I then found another data set from Chicago
Tribune which lists every single school that faced budget cuts, as well as how
much their budget increased or was slashed. I'll either try to find some way to
indicate this on the map I am conjuring in my mind currently, or perhaps
construct an additional graph. I have web scraped all the necessary data I 
wanted in the gather.Rmd file, and am prepared to work with them now. I have
contacted CPS to see if there is any more information I can obtain to add
to my repertoire of data, but I am prepared to start researching how I can
animate a geographic graph of the CPS district with the data.

Here are the links to my sources:

https://interactive.wbez.org/generation-school-closings/

https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vRmKox-lDNqhtUNL4WLl8x6DljIi3b0k1pYEmD7adfCwX-rGYyFw0XIjxNWkOfL6og3CHfUEHPMwv6k/pubhtml?urp=gmail_link#

https://www.chicagotribune.com/news/ct-2016-cps-school-budget-cuts-table-htmlstory.html







