---
title: "data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(tidyverse)
library(janitor)  
library(gt)
library(dplyr)
library(rvest)
library(ggplot2)
```

```{r}
e2007 <- read_csv('enrollment_2007.csv', col_types = cols(
  Area = col_double(),
  Unit = col_double(),
  `School ID` = col_double(),
  School = col_character(),
  Total = col_number(),
  Year = col_double()))

e2008 <- read_csv('enrollment_2008.csv', col_types = cols(
  Area = col_double(),
  Unit = col_double(),
  `School ID` = col_double(),
  Schools = col_character(),
  Total = col_number(),
  year = col_double()))

e2009 <- read_csv('enrollment_2009.csv', col_types = cols(
  Area = col_double(),
  Unit = col_double(),
  `School ID` = col_double(),
  Schools = col_character(),
  Totals = col_number(),
  year = col_double()))

e2010 <- read_csv('enrollment_2010.csv', col_types = cols(
  Area = col_double(),
  Unit = col_double(),
  `School ID` = col_double(),
  Schools = col_character(),
  Totals = col_number(),
  year = col_double()))

e2011 <- read_csv('enrollment_2011.csv', col_types = cols(
  Area = col_double(),
  Unit = col_double(),
  `School ID` = col_double(),
  Schools = col_character(),
  Totals = col_number(),
  year = col_double()))

e2012 <- read_csv('enrollment_2012.csv', col_types = cols(
  Network = col_character(),
  Unit = col_double(),
  `School ID` = col_double(),
  School = col_character(),
  Totals = col_number(),
  year = col_double()))

e2013 <- read_csv('enrollment_2013.csv', col_types = cols(
  Network = col_character(),
  `School ID` = col_double(),
  School = col_character(),
  Totals = col_number(),
  year = col_double()))



```

