---
title: "Final Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(tidyverse)
library(janitor)  
library(gt)
library(dplyr)
library(rvest)
library(ggplot2)
library(sf)
library(broom)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggmap)
```

```{r include = FALSE}
# schools <- read_csv('schools.csv') 

school2 <- read_csv('data/schools.csv', skip = 1,
  na = c("undefined", ""),
  col_types = cols(
  school = col_double(),
  address = col_character(),
  zip = col_character(),
  year = col_double(),
  type = col_character(),
  use = col_character(),
  '2_plus' = col_double(),
  private = col_double(),
  sold = col_character(),
  buyer = col_character(),
  price = col_character())) 

budget <- read_csv('data/budget_data.csv')

locs <- read_csv('data/CPS_School_Locations_SY1415.csv')
```

```{r echo = FALSE}
graph <- school2 %>% 
  group_by(year) %>% 
  filter(type == "school closing") %>% 
  count(type) %>% 
  ggplot(aes(year, n)) +
  geom_line() +
  labs(x = "Year", 
       y = "Number of School Closings", 
       title = "Number of School Closings in CPS from 2002-2018") +
  scale_x_continuous(breaks = seq(2002, 2018, by = 1)) +
  theme_light() +
  theme(plot.title = element_text(face = "bold", color = "#063376", size = 20))


school_join <- school2 %>% 
  group_by(year) %>% 
  filter(type == "school closing") %>% 
  filter(year > 2006 && year < 2019) %>% 
  count(type) 

ejoin <- enrollment %>% 
  filter(!is.na(Total)) %>% 
  group_by(Year) %>% 
  summarize(sum = sum(Total)) %>% 
  rename("year" = Year)

school_e_join <- ejoin %>%
  inner_join(school_join, by = "year") 

school_e_join %>%
  ggplot(aes(n, sum, color = year)) +
  geom_point(show.legend = FALSE, alpha = 0.7) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", se = TRUE)

# Fit regression model:

correlation <- school_e_join %>%
  summarize(correlation = cor(sum, n))

correlation

school_e_join %>%
  lm(sum ~ n, data = .) %>%
  tidy(conf.int = TRUE)

aid2 <- aid %>% 
  filter(year < 2019) %>% 
  inner_join(ejoin, by = "year")

aid2 %>% 
  ggplot(aes(gap, sum, color = year)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm", se = TRUE)

aid2 %>% 
  lm(sum ~ gap, data = .) %>% 
  tidy(conf.int = TRUE)

aid2 %>% 
summarize(correlation = cor(sum, gap))


  

```
Map

```{r}
library(tidycensus)
census_api_key('9f9584127dd506cdaf80bdb78927e9c01c12f2b8', overwrite = TRUE)

locs3 <- locs %>% 
  select(X, Y)

locx <- locs3 %>% 
  pull(X)

locy <- locs3 %>% 
  pull(Y)

racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005",
              Hispanic = "B03003_003")
cook <- get_acs(geography = "tract",
                  variables = racevars, 
                  year = 2018,
                  state = "IL",
                  county = "Cook",
                  geometry = TRUE,
                  summary_var = "B02001_001") 

sites <- data.frame(longitude = locx, latitude = locy)


cook %>%
  mutate(Percent = 100 * (estimate / summary_est)) %>%
  ggplot() +
  geom_sf() +
  geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = 23, fill = "darkred") +
  scale_fill_viridis_c(direction = -1) +
  scale_color_viridis_c(direction = -1) +
  labs(title = "Racial geography of Cook County, Illinois",
       caption = "Source: American Community Survey 2014-2018") 
  # theme_void()




```

```{r}
aid3 <- aid2 %>% 
  filter(year < 2015)

drop_join <- dropout %>% 
  filter(year > 2006) %>% 
  inner_join(aid3) %>% 
  mutate(total_aid = state_aid + federal_aid) 

drop_join %>% 
  ggplot(aes(x = total_dropout, y = state_aid, color = year)) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE) +
  scale_x_log10() +
  scale_y_log10() 

 drop_join %>% 
  lm(federal_aid ~ total_dropout, data = .) %>%
  tidy(conf.int = TRUE)
 
 cor2 <- drop_join %>%
  summarize(correlation = cor(federal_aid, total_dropout))
 
 cor2
 
 p <- drop_join %>% 
   group_by(group) %>% 
   summarize(Correlation = cor(state_aid, total_dropout)) %>% 
   rename(Group = group) %>% 
   select(Group, Correlation) %>% 
   gt() %>% 
   tab_header(
    title = "Correlation Coefficients of State Aid & Student Groups",
    subtitle = "Data spans 2007-2014") %>% 
   tab_spanner(
    label = "Coefficients",
    columns = c("Group", "Correlation"))
 
 p


# s <- aid3 %>% 
#   ggplot(aes(year, gap)) +
#   geom_line() +
#   labs(x = "Year", 
#        y = "Amount (in millions of dollars)") +
#     transition_reveal(year)
```

